### ISSUE TITLE
How to run on gpu

### ISSUE THREAD

**Issue by Draconda** [iarai/NeurIPS2021-traffic4cast#6]
from official usage, I used

```
export PYTHONPATH="$PYTHONPATH:$PWD"

DEVICE=cuda
DATA_RAW_PATH="./data/raw"
GROUND_TRUTH=""

python baselines/baselines_cli.py --model_str=unet          --limit=2 --epochs=1 --batch_size=1 --num_workers=1 --data_raw_path=$DATA_RAW_PATH --device=$DEVICE $GROUND_TRUTH
```

, but it causes

```
AssertionError: Torch not compiled with CUDA enabled
```

1gpu has set into this environment,
is this right usage?

Thanks,

**Comment by moritz9** [comment]
Hi Draconda,
Looks like this is due to your current PyTorch installation. If you did create the environment using the provided file (https://github.com/iarai/NeurIPS2021-traffic4cast/blob/master/environment.yaml) you need to enable GPU in it, see line 16 to 19. If you have a different setup, please check https://pytorch.org/ for a GPU-enabled installation.
Best regards,
Moritz

**Comment by Draconda** [comment]
Hi Moritz,

Thank you for reply,
I was trying to fix this, at first I cleared environment & conda update with changing line 17, but seems

"""
- cudatoolkit=11.1
"""

causes 

"""
PackagesNotFoundError: The following packages are not available from current channels
"""

, then I tried 

"""
- cudatoolkit=11.0
"""

this works, but it still causes 

"""
AssertionError: Torch not compiled with CUDA enabled
"""

. then I'm trying to change line 19
"""
- cpuonly
"""

& re-creating environment, but having difficulty...

how to change here?

thanks,

Draconda

**Comment by moritz9** [comment]
Hi Draconda,

you might have to add the conda-forge channel to your setup before creating the environment. This can be done with `conda config --append channels conda-forge`

With that the following lines 16-19 should work:
```
# uncomment for gpu support
  - cudatoolkit=11.1
# comment out for gpu support
#  - cpuonly # replace cpuonly with your cuda version for GPU support
```

After `conda env update -f environment.yaml` and `conda activate t4c` you can verify the installation with
```
$ python
Python 3.8.11 (default, Aug  3 2021, 15:09:35) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>
```

Hope this helps,
Moritz

**Comment by Draconda** [comment]
Hi Moritz!

Thanks for quick reply,
at first I cleared current t4c env & run
```conda config --append channels conda-forge```
, after that I run
```conda env update -f environment.yaml```
, &checked ```torch.cuda.is_available()``` is True.
but when I run training this code;
```
export PYTHONPATH="$PYTHONPATH:$PWD"

DEVICE=cuda
DATA_RAW_PATH="./data/raw"
GROUND_TRUTH=""

python baselines/baselines_cli.py --model_str=unet          --limit=2 --epochs=1 --batch_size=1 --num_workers=1 --data_raw_path=$DATA_RAW_PATH --device=$DEVICE $GROUND_TRUTH
```

I had
```
Traceback (most recent call last):
  File "baselines/baselines_cli.py", line 24, in <module>
    import torch_geometric
  File "/home/r_ishizaki/workspace/draco00/code/code/test00/envs/t4c-cuda/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/r_ishizaki/workspace/draco00/code/code/test00/envs/t4c-cuda/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/r_ishizaki/workspace/draco00/code/code/test00/envs/t4c-cuda/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/r_ishizaki/workspace/draco00/code/code/test00/envs/t4c-cuda/lib/python3.8/site-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```

Did you have this error too?

Thanks,
Draconda

**Comment by chenkins** [comment]
@Draconda does https://github.com/rusty1s/pytorch_sparse/issues/127  help? If you only need the unet, comment out the corresponding imports in `baselines_cli.py`. Unfortunately, a robust setup seems a bit tricky.

**Comment by Draconda** [comment]
@chenkins 

Finally it worked!

seems torch_geometric for gcn has harsh version conflicts for some libraries, then I removed all of them & it runs well on unet,
cpu -> gpu titan x makes training faster about 2.18 times,

Anyway thanks again for both @chenkins and @moritz9 !

Draconda
